[package]
name = "tomp-http-tower-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["query"] }
common = { path = "../common" }
futures-util = "0.3.32"
memory-stats = "1.2.0"
moka = { version = "0.12.15", features = ["future"] }
rand = "0.10.1"
reqwest = { version = "0.13.3", default-features = false, features = ["rustls", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sync_wrapper = { version = "1.0.2", features = ["futures"] }
tokio = { version = "1.52.3", features = ["macros"] }
tokio-websockets = { version = "0.13.3", features = ["client", "rand", "server", "sha1_smol"] }
tokio-websockets-axum = { path = "../tokio-websockets-axum/" }
tower = "0.5.3"
tower-http = { version = "0.6.10", features = ["cors"] }
tracing = "0.1.44"

[dev-dependencies]
argh = "0.1.19"
axum = { version = "0.8.9", default-features = false, features = ["http1", "query", "tokio", "original-uri"] }
tokio = { version = "1.52.3", features = ["net", "rt-multi-thread", "signal"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tower-http = { version = "0.6.10", features = ["cors"] }
