[package]
name = "static-client-tower-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["query"] }
num-traits = "0.2.19"
tower = "0.5.3"
tower-etag-cache = { path = "../tower-etag-cache-0.1.0", features = ["const-lru-provider"] }
tower-http = { version = "0.6.10", features = ["compression-br", "compression-deflate", "compression-gzip", "compression-zstd"] }